"""Crear tablas iniciales

Revision ID: ab85b162da07
Revises: 
Create Date: 2025-12-09 13:29:15.908992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab85b162da07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('empresa', sa.String(length=255), nullable=True),
    sa.Column('producto', sa.String(length=255), nullable=True),
    sa.Column('tasa_descuento', sa.Float(), nullable=False),
    sa.Column('tasa_impuestos', sa.Float(), nullable=True),
    sa.Column('periodos', sa.Integer(), nullable=True),
    sa.Column('inversion_inicial', sa.Float(), nullable=True),
    sa.Column('unidades_produccion', sa.Integer(), nullable=True),
    sa.Column('precio_venta_unitario', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('gantt_data', sa.Text(), nullable=True),
    sa.Column('sensibilidad_data', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('costos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('periodo_0', sa.Float(), nullable=True),
    sa.Column('periodo_1', sa.Float(), nullable=True),
    sa.Column('periodo_2', sa.Float(), nullable=True),
    sa.Column('periodo_3', sa.Float(), nullable=True),
    sa.Column('periodo_4', sa.Float(), nullable=True),
    sa.Column('costo_unitario', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flujo_efectivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('periodo_0', sa.Float(), nullable=True),
    sa.Column('periodo_1', sa.Float(), nullable=True),
    sa.Column('periodo_2', sa.Float(), nullable=True),
    sa.Column('periodo_3', sa.Float(), nullable=True),
    sa.Column('periodo_4', sa.Float(), nullable=True),
    sa.Column('descontado_0', sa.Float(), nullable=True),
    sa.Column('descontado_1', sa.Float(), nullable=True),
    sa.Column('descontado_2', sa.Float(), nullable=True),
    sa.Column('descontado_3', sa.Float(), nullable=True),
    sa.Column('descontado_4', sa.Float(), nullable=True),
    sa.Column('acumulado_0', sa.Float(), nullable=True),
    sa.Column('acumulado_1', sa.Float(), nullable=True),
    sa.Column('acumulado_2', sa.Float(), nullable=True),
    sa.Column('acumulado_3', sa.Float(), nullable=True),
    sa.Column('acumulado_4', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proyecto_id')
    )
    op.create_table('indicadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('van', sa.Float(), nullable=True),
    sa.Column('tir', sa.Float(), nullable=True),
    sa.Column('ir', sa.Float(), nullable=True),
    sa.Column('relacion_bc', sa.Float(), nullable=True),
    sa.Column('payback', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('total_ingresos', sa.Float(), nullable=True),
    sa.Column('total_egresos', sa.Float(), nullable=True),
    sa.Column('utilidad_bruta', sa.Float(), nullable=True),
    sa.Column('utilidad_neta', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('calculado_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proyecto_id')
    )
    op.create_table('ingresos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('periodo_0', sa.Float(), nullable=True),
    sa.Column('periodo_1', sa.Float(), nullable=True),
    sa.Column('periodo_2', sa.Float(), nullable=True),
    sa.Column('periodo_3', sa.Float(), nullable=True),
    sa.Column('periodo_4', sa.Float(), nullable=True),
    sa.Column('unidades_periodo_1', sa.Integer(), nullable=True),
    sa.Column('unidades_periodo_2', sa.Integer(), nullable=True),
    sa.Column('unidades_periodo_3', sa.Integer(), nullable=True),
    sa.Column('unidades_periodo_4', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingresos')
    op.drop_table('indicadores')
    op.drop_table('flujo_efectivo')
    op.drop_table('costos')
    op.drop_table('proyectos')
    # ### end Alembic commands ###
